# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='SearchTerm',
        ),
    ]
